// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import notify from 'devextreme/ui/notify';
import { DxSwitchTypes } from 'devextreme-angular/ui/switch';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss'],
    standalone: false
})
export class AppComponent {
  switchValue = true;

  onValueChanged(e: DxSwitchTypes.ValueChangedEvent): void {
    const message = e.value ? 'Switch is ON' : 'Switch is OFF';
    notify(message, 'info', 1000);
  }
}

<dx-switch
    [value]="false"
    [width]="80"
    [rtlEnabled]="true"
    [hint]="hintMessage"
    (onValueChanged)="onValueChanged($event)"
>
</dx-switch>

// Vue/src/App.vue
<template>
    <DxSwitch 
        :value="false"
        :width="80"
        :rtlEnabled="true"
        :hint="hintMessage"
        @value-changed="onValueChanged($event)"
    > </DxSwitch>
</template>

<script>
import "devextreme/dist/css/dx.light.css";
import { DxSwitch } from "devextreme-vue/switch";
import notify from "devextreme/ui/notify";

export default {
    components: {
        DxSwitch
    },
    data() {
        return {
            hintMessage: "Click to switch on",
        };
    },
    methods: {
        onValueChanged(e) {
            this.hintMessage = e.value ? "Click to switch off" : "Click to switch on";
            const stateLabel = e.value ? "ON" : "OFF";
            notify(`The component is switched ${stateLabel}`);
        }
    }
}
</script>
