// React/src/orig_App.js
import React, { useState, useCallback } from "react";
import "devextreme/dist/css/dx.light.css";

import { Switch } from "devextreme-react/switch";
import notify from "devextreme/ui/notify";

function App() {
    const [hintMessage, setHintMessage] = useState("Click to switch on");

    const onValueChanged = useCallback((e) => {
        const messageText = e.value ? "Click to switch off" : "Click to switch on";
        const stateLabel = e.value ? "ON" : "OFF";
        setHintMessage(messageText);
        notify(`The component is switched ${stateLabel}`); 
    }, []);
    
    return (
        <Switch 
            value={false}
            width={80}
            rtlEnabled={true}
            hint={hintMessage}
            onValueChanged={onValueChanged}
        />
    );
}

export default App;

// Angular/src/app/orig_app.component.ts
import { Component } from "@angular/core";
import notify from "devextreme/ui/notify";

@Component({
    selector: "app-root",
    templateUrl: "./app.component.html",
    styleUrls: ["./app.component.css"]
})

export class AppComponent {
    hintMessage: string = "Click to switch on";
    onValueChanged(e: {value: boolean}) {
        this.hintMessage = e.value ? "Click to switch off" : "Click to switch on";
        const stateLabel = e.value ? "ON" : "OFF";
        notify(`The component is switched ${stateLabel}`); 
    }
}
